version: "3.6"
services:
  workbench:
    image: linuxserver/webtop:ubuntu-kde
    ports:
      - "3000:3000"
    #shm_size: "1gb" #optional
    #restart: unless-stopped
    #volumes:
      #- workbench0:/config
      #- /var/run/docker.sock:/var/run/docker.sock

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Colorado
      #- SUBFOLDER=/ #optional
    networks:
      #- default
      - Inner-Athena
      - traefik-public
    deploy:
      labels:
        - traefik.port=3000
        - traefik.frontend.rule=Host(`workbench.underground-ops.me`)
        # To hash password use (openssl passwd -apr1 | sed -E "s:[\$]:\$\$:g") - default password is "notiaPoint!1"
        - traefik.http.middlewares.workbench-auth.basicauth.users=admin:$$apr1$$nIkVDmwy$$xkGIleRnQ0GJ6o96am.cb/
        - traefik.docker.network=proxy
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # https-redirect middleware to redirect HTTP to HTTPS
        # It can be re-used by other stacks in other Docker Compose files
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.workbench-http.rule=Host(`workbench.underground-ops.me`)
        - traefik.http.routers.workbench-http.entrypoints=http
        - traefik.http.routers.workbench-http.middlewares=https-redirect
        - traefik.http.routers.workbench-https.rule=Host(`workbench.underground-ops.me`)
        - traefik.http.routers.workbench-https.entrypoints=https
        - traefik.http.routers.workbench-https.tls=true
        # Use the "le" (Let's Encrypt) resolver created below
        - traefik.http.routers.workbench-https.tls.certresolver=le
        # Enable HTTP Basic auth, using the middleware created above
        - traefik.http.routers.workbench-https.middlewares=workbench-auth
        - traefik.http.services.workbench.loadbalancer.server.port=3000

#volumes:
  #workbench0:
    #external: true
networks:
  Inner-Athena:
    external: true
  traefik-public:
    external: true

