# =============================================================================
# PREVIEW ONLY - deploy-olympiad.sh (FULL flavor) as generated by simulating
# the upgraded Dockerfile's echo-chain. Source of truth is the Dockerfile.
# Host ports show as ${P_SSH}/${P_DNS}/${P_DHCP}/${P_S3}: resolved at RUN time
# by detect_substrate (canonical in a container, shifted on bare metal).
# (kubectl-version curl lookups render empty here because the sim has no
#  network; during a real build they resolve live, exactly as before.)
# =============================================================================

#!/bin/sh
log() { echo "[olympiad] $*"; }
wait_docker() { i=0; until docker info >/dev/null 2>&1; do i=$((i+1)); [ "$i" -ge 180 ] && { log "dockerd not ready after 180s - continuing best-effort"; return 1; }; [ $((i % 5)) -eq 0 ] && log "waiting for docker daemon... ($i)"; sleep 1; done; log "docker daemon ready"; }
wait_container() { n="$1"; i=0; until [ "$(docker inspect -f "{{.State.Running}}" "$n" 2>/dev/null)" = "true" ]; do i=$((i+1)); [ "$i" -ge 120 ] && { log "$n not running after 120s - continuing"; return 1; }; sleep 1; done; log "$n running"; }
wait_exec() { n="$1"; wait_container "$n" || true; i=0; until docker exec "$n" true >/dev/null 2>&1; do i=$((i+1)); [ "$i" -ge 120 ] && { log "$n not exec-ready after 240s - continuing"; return 1; }; sleep 2; done; log "$n exec-ready"; }
retry() { n=0; until "$@"; do n=$((n+1)); [ "$n" -ge 5 ] && { log "failed after 5 tries: $*"; return 1; }; log "retry $n/5: $*"; sleep 3; done; }
ensure_net_bridge() { docker network inspect "$1" >/dev/null 2>&1 && { log "net $1 exists"; return 0; }; M=$(net_mtu); if [ -n "$M" ]; then log "net $1 creating with mtu=$M"; retry docker network create -d bridge --opt com.docker.network.driver.mtu="$M" --subnet="$2" --gateway="$3" "$1"; else retry docker network create -d bridge --subnet="$2" --gateway="$3" "$1"; fi; }
ensure_net_overlay() { docker network inspect "$1" >/dev/null 2>&1 && { log "net $1 exists"; return 0; }; retry docker network create -d overlay --subnet="$2" "$1"; }
net_mtu() { case "${NEXUS_NET_MTU:-}" in "") : ;; auto) I=$(ip -4 route show default 2>/dev/null | awk "{print \$5; exit}"); [ -z "$I" ] && I=$(ls /sys/class/net 2>/dev/null | grep -v "^lo$" | head -1); [ -n "$I" ] && cat /sys/class/net/"$I"/mtu 2>/dev/null ;; *) echo "${NEXUS_NET_MTU}" ;; esac; }
net_report() { R=$(docker network inspect "$1" --format "driver={{.Driver}} subnet={{range .IPAM.Config}}{{.Subnet}}{{end}} gw={{range .IPAM.Config}}{{.Gateway}}{{end}} mtu={{index .Options \"com.docker.network.driver.mtu\"}}" 2>/dev/null | sed "s/mtu=<no value>/mtu=default/"); log "net $1 $R"; }
ensure_repo() { if [ -d /nexus-bucket/underground-nexus/.git ]; then git -C /nexus-bucket/underground-nexus pull --rebase >/dev/null 2>&1 || true; else mkdir -p /nexus-bucket; retry git clone https://github.com/Underground-Ops/underground-nexus.git /nexus-bucket/underground-nexus || true; fi; }
pkg_add() { command -v "$1" >/dev/null 2>&1 && return 0; apk add --no-cache "$2" >/dev/null 2>&1 || { apt-get update >/dev/null 2>&1 && apt-get install -y "$2" >/dev/null 2>&1; } || dnf install -y "$2" >/dev/null 2>&1 || true; command -v "$1" >/dev/null 2>&1; }
ensure_compose() { pkg_add docker-compose docker-compose || log "docker-compose not installable here - compose steps degrade"; }
ensure_swarm() { docker node ls >/dev/null 2>&1 && { log "swarm already active - joining existing"; return 0; }; docker swarm init >/dev/null 2>&1 && { log "swarm init ok"; return 0; }; A=$(ip -4 route get 1.1.1.1 2>/dev/null | awk "{print \$7; exit}"); [ -z "$A" ] && A=$(hostname -i 2>/dev/null | awk "{print \$1}"); [ -n "$A" ] && docker swarm init --advertise-addr "$A" >/dev/null 2>&1 && { log "swarm init ok (advertise $A)"; return 0; }; log "swarm init failed - overlay nets may degrade to bridge"; return 1; }
detect_substrate() { if [ -f /.dockerenv ] || [ -f /run/.containerenv ]; then NEXUS_METAL=0; else NEXUS_METAL=1; fi; DOCKER_BIN=$(command -v docker 2>/dev/null || echo /usr/local/bin/docker); NEXUS_ARCH=$(uname -m); if [ "$NEXUS_METAL" = "1" ]; then P_SSH="${P_SSH:-2223}"; P_DNS="${P_DNS:-5353}"; P_DHCP="${P_DHCP:-6767}"; P_S3="${P_S3:-19000}"; log "substrate: bare metal ($NEXUS_ARCH) - host publishes shifted ssh=$P_SSH dns=$P_DNS dhcp=$P_DHCP s3=$P_S3"; else P_SSH="${P_SSH:-22}"; P_DNS="${P_DNS:-53}"; P_DHCP="${P_DHCP:-67}"; P_S3="${P_S3:-9000}"; log "substrate: container ($NEXUS_ARCH) - canonical host publishes"; fi; log "docker cli at $DOCKER_BIN"; }

# ---- preflight (added): wait for dockerd, ensure repo, clean slate ----
wait_docker
detect_substrate
pkg_add git git || log "git unavailable - repo sync may skip"
ensure_repo
[ "${OLYMPIAD_CLEAN:-1}" = "1" ] && for c in Inner-DNS-Control Olympiad0 Athena0 Security-Operation-Center workbench torpedo code-server Nexus-Secret-Vault; do docker rm -f "$c" >/dev/null 2>&1 || true; done
ensure_swarm || true
ensure_compose
ensure_net_bridge Inner-Athena 10.20.0.0/24 10.20.0.1
net_report Inner-Athena
docker run -itd -p ${P_DNS}:53/tcp -p ${P_DNS}:53/udp -p ${P_DHCP}:67 -p 800:80 -h Inner-DNS-Control --name=Inner-DNS-Control --net=Inner-Athena --ip=10.20.0.20 --restart=always -v pihole_DNS_data:/etc/dnsmasq.d/ -v pihole_config:/etc/pihole/ pihole/pihole:latest || true
wait_container Inner-DNS-Control
docker volume create portainer_data
docker run -d -p 8000:8000 -p 9443:9443 --name=Olympiad0 --dns=10.20.0.20 --net=Inner-Athena --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest || true
docker run -itd --init --privileged -p ${P_SSH}:22 --name=Athena0 -h Athena0 --dns=10.20.0.20 --net=Inner-Athena --restart=always -v athena0:/home/ -v /nexus-bucket:/nexus-bucket -v /etc/docker:/etc/docker -v ${DOCKER_BIN}:/usr/local/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes/:/var/lib/docker/volumes/ natoascode/athena0:latest || true
docker run -itd --name=Security-Operation-Center -h Security-Operation-Center -e PUID=2000 -e PGID=2000 -e TZ=America/Colorado -p 2000:3001 --dns=10.20.0.20 --net=Inner-Athena --ip=10.20.0.30 --restart=always -v security-operation-center:/config -v /nexus-bucket:/config/Desktop/nexus-bucket linuxserver/webtop:ubuntu-i3 || true
wait_exec Security-Operation-Center
docker exec Security-Operation-Center apt update || true
docker exec Security-Operation-Center apt install rofi -y || true
docker exec Security-Operation-Center apt install terminator -y || true
docker exec Security-Operation-Center apt install firefox -y || true
docker exec Security-Operation-Center su - abc -c 'DISPLAY=:1 firefox &' || true
docker exec Security-Operation-Center su - abc -c 'DISPLAY=:1 terminator &' || true
echo FROM natoascode/workbench0:ubuntu >> /nexus-bucket/workbench.dockerfile
echo RUN bash workbench.sh >> /nexus-bucket/workbench.dockerfile
docker build -f /nexus-bucket/workbench.dockerfile -t workbench:latest /nexus-bucket
docker run -itd  --privileged --name=workbench -h workbench -e PUID=1000 -e PGID=1000 -e TZ=America/Colorado -p 1000:3000 --dns=10.20.0.20 --net=Inner-Athena --restart=always -v /dev:/dev -v workbench0:/config -v /nexus-bucket:/config/Desktop/nexus-bucket -v /var/run/docker.sock:/var/run/docker.sock natoascode/workbench0:ubuntu || true
wait_exec workbench
docker exec workbench bash /workbench.sh || true
docker exec workbench sudo apt install firefox -y || true
docker run -itd  --privileged --name=workbench -h workbench -e PUID=1000 -e PGID=1000 -e TZ=America/Colorado -p 1000:3000 --dns=10.20.0.20 --net=Inner-Athena --restart=always -v /dev:/dev -v workbench0:/config -v /nexus-bucket:/config/Desktop/nexus-bucket -v /var/run/docker.sock:/var/run/docker.sock workbench:latest || true
docker exec workbench echo docker exec workbench sudo apt -y update >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo apt install -y wget >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec Security-Operation-Center sudo apk update >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec Security-Operation-Center sudo apk add wget >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec Security-Operation-Center sudo apk add dpkg >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec Security-Operation-Center sudo apk upgrade >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo apt install -y git >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo apt install -y iputils-ping >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo wget https://raw.githubusercontent.com/Underground-Ops/underground-nexus/main/github-desktop.sh >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo bash github-desktop.sh >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo apt install -y apt-transport-https curl >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo dpkg -i chrome-remote-desktop_current_amd64.deb >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench wget https://release.gitkraken.com/linux/gitkraken-amd64.deb >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo dpkg -i gitkraken-amd64.deb >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo dpkg -i discord.deb >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo apt install -y qemu >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo apt install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils qemu-system qemu-system-x86 qemu-system-arm >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo apt install -y virt-manager >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo apt install -y synaptic >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo apt install -y terminator >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec Athena0 wget https://raw.githubusercontent.com/rancher/k3d/main/install.sh >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec Athena0 bash /install.sh >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec Athena0 k3d cluster create KuberNexus --network Inner-Athena --api-port 10.20.0.1:6443 -p 18080:8080@loadbalancer -p 8443:8443@loadbalancer -p 2222:22@loadbalancer -p 179:179@loadbalancer -p 2375:2376@loadbalancer -p 2378:2379@loadbalancer -p 2381:2380@loadbalancer -p 8472:8472@loadbalancer -p 8843:443@loadbalancer -p 4789:4789@loadbalancer -p 9099:9099@loadbalancer -p 9100:9100@loadbalancer -p 7443:9443@loadbalancer -p 9796:9796@loadbalancer -p 6783:6783@loadbalancer -p 10250:10250@loadbalancer -p 10254:10254@loadbalancer -p 31896:31896@loadbalancer -v /nexus-bucket:/nexus-bucket -v /dev:/dev --servers 1 --registry-create KuberNexus-registry --kubeconfig-update-default >> /nexus-bucket/build-kubernexus.sh
docker exec workbench echo docker exec Athena0 export KUBECONFIG=/root/.k3d/kubeconfig-KuberNexus.yaml >> /nexus-bucket/build-kubernexus.sh
docker exec workbench echo docker exec Athena0 k3d kubeconfig merge KuberNexus --kubeconfig-merge-default >> /nexus-bucket/build-kubernexus.sh
docker exec workbench echo docker exec Athena0 sh /nexus-bucket/build-kubernexus.sh >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec Athena0 sh /enable-weekly-updates.sh >> /nexus-bucket/enable-weekly-updates.sh
docker exec workbench echo docker exec workbench sudo wget https://raw.githubusercontent.com/Underground-Ops/underground-nexus/main/Terraform%20Master/terraform-workbench-install.sh >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo sh terraform-workbench-install.sh >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo mv /terraform-workbench-install.sh /config/Desktop/nexus-bucket >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo apt -y update --fix-missing >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo apt --fix-broken install -y >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo apt -y upgrade >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo apt install -y virt-manager firefox >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo rm /usr/share/backgrounds/ubuntu-mate-jammy/Jammy-Jellyfish_WP_4096x2304_Green.png >> /nexus-bucket/workbench.sh
docker exec workbench echo docker exec workbench sudo wget https://raw.githubusercontent.com/Underground-Ops/underground-nexus/main/Wallpapers/underground-nexus-scifi-space-jelly.png -O /usr/share/backgrounds/ubuntu-mate-jammy/Jammy-Jellyfish_WP_4096x2304_Green.png >> /nexus-bucket/workbench.sh
wait_exec Athena0
docker exec Athena0 apt -y update
docker exec Athena0 apt install -y iputils-ping
docker exec Athena0 git clone https://github.com/radareorg/radare2
docker exec Athena0 sh radare2/sys/install.sh
docker exec Athena0 apt-get install -y metasploit-framework
docker exec Athena0 apt -y update
docker exec Athena0 apt -y upgrade
docker run -itd --privileged -p ${P_S3}:9000 -p 9010:9001 --name=torpedo -h torpedo --dns=10.20.0.20 --net=Inner-Athena --restart=always -v /nexus-bucket:/nexus-bucket -v /nexus-bucket/s3-torpedo:/data pgsty/minio:latest server /data --console-address ":9001" || true
docker run -d --name=code-server -e PUID=1050 -e PGID=1050 -p 18443:3000 --dns=10.20.0.20 --net=Inner-Athena -v /nexus-bucket:/nexus-bucket -v /nexus-bucket/visual-studio-code:/config -v /etc/docker:/etc/docker -v ${DOCKER_BIN}:/usr/local/bin/docker -v /var/run/docker.sock:/var/run/docker.sock --restart unless-stopped lscr.io/linuxserver/openvscode-server || true
docker run -itd -p 8200:1234 --name=Nexus-Secret-Vault -h Nexus-Secret-Vault --dns=10.20.0.20 --net=Inner-Athena --restart=always --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=myroot' -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:1234' hashicorp/vault:1.13.3 || true
docker exec Athena0 sh /old-underground-nexus-dagger-ci.sh
docker exec Athena0 sh /nexus-bucket/underground-nexus/'Dagger CI'/Scripts/enable-weekly-updates.sh
docker exec workbench echo docker exec workbench bash /config/Desktop/nexus-bucket/underground-nexus/visual-studio-code.sh >> /nexus-bucket/workbench.sh
docker exec Athena0 sh /nexus-bucket/workbench.sh
docker restart Inner-DNS-Control
curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
#k3d cluster create KuberNexus -p 8080:8080@loadbalancer -p 8443:8443@loadbalancer -p 2222:22@loadbalancer -p 179:179@loadbalancer -p 2375:2376@loadbalancer -p 2378:2379@loadbalancer -p 2381:2380@loadbalancer -p 8472:8472@loadbalancer -p 8843:443@loadbalancer -p 4789:4789@loadbalancer -p 9099:9099@loadbalancer -p 9100:9100@loadbalancer -p 7443:9443@loadbalancer -p 9796:9796@loadbalancer -p 6783:6783@loadbalancer -p 10250:10250@loadbalancer -p 10254:10254@loadbalancer -p 31896:31896@loadbalancer -v /nexus-bucket:/nexus-bucket --servers 3 --registry-create KuberNexus-registry --kubeconfig-update-default
curl -LO https://dl.k8s.io/release//bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
k3d kubeconfig merge KuberNexus --kubeconfig-merge-default
docker exec Athena0 bash /nexus-bucket/underground-nexus/'Dagger CI'/Scripts/virtual-machine-engine.sh
ensure_net_overlay underground-wordpress_internal 172.16.32.0/24
curl https://raw.githubusercontent.com/Underground-Ops/underground-nexus/main/Dagger%20CI/Scripts/gitlab-collaborator-stack.sh | sh
wget https://raw.githubusercontent.com/Underground-Ops/underground-nexus/main/Production%20Artifacts/firefox-homepage.sh
sh firefox-homepage.sh
docker exec workbench bash /config/Desktop/nexus-bucket/terraform-workbench-install.sh && docker exec workbench terraform -v && docker exec workbench apt install terminator -y && docker exec workbench chown -R abc /config
docker exec workbench bash /config/Desktop/nexus-bucket/underground-nexus/'Dagger CI'/Scripts/Maintenance/workbench-apt-update-repair.sh
docker exec workbench apt install rofi -y
docker exec workbench bash /config/Desktop/nexus-bucket/underground-nexus/'Dagger CI'/Scripts/configure-desktop-menu.sh
docker exec workbench bash /config/Desktop/nexus-bucket/underground-nexus/Jelly-Apps/Git-BIOS-Control-Panel/install-git-bios-control-panel.sh || true
docker exec Athena0 curl https://raw.githubusercontent.com/Underground-Ops/underground-nexus/main/underground-nexus-update.sh | bash
docker restart Inner-DNS-Control
docker restart workbench
docker restart Athena0