# =============================================================================
# PREVIEW ONLY - deploy-olympiad-light.sh (LIGHT flavor, 8GB Pi minimum viable)
# as generated by simulating the upgraded Dockerfile's echo-chain.
# Source of truth is the Dockerfile.
# =============================================================================

#!/bin/sh
log() { echo "[olympiad] $*"; }
wait_docker() { i=0; until docker info >/dev/null 2>&1; do i=$((i+1)); [ "$i" -ge 180 ] && { log "dockerd not ready after 180s - continuing best-effort"; return 1; }; [ $((i % 5)) -eq 0 ] && log "waiting for docker daemon... ($i)"; sleep 1; done; log "docker daemon ready"; }
wait_container() { n="$1"; i=0; until [ "$(docker inspect -f "{{.State.Running}}" "$n" 2>/dev/null)" = "true" ]; do i=$((i+1)); [ "$i" -ge 120 ] && { log "$n not running after 120s - continuing"; return 1; }; sleep 1; done; log "$n running"; }
wait_exec() { n="$1"; wait_container "$n" || true; i=0; until docker exec "$n" true >/dev/null 2>&1; do i=$((i+1)); [ "$i" -ge 120 ] && { log "$n not exec-ready after 240s - continuing"; return 1; }; sleep 2; done; log "$n exec-ready"; }
retry() { n=0; until "$@"; do n=$((n+1)); [ "$n" -ge 5 ] && { log "failed after 5 tries: $*"; return 1; }; log "retry $n/5: $*"; sleep 3; done; }
ensure_net_bridge() { docker network inspect "$1" >/dev/null 2>&1 && { log "net $1 exists"; return 0; }; M=$(net_mtu); if [ -n "$M" ]; then log "net $1 creating with mtu=$M"; retry docker network create -d bridge --opt com.docker.network.driver.mtu="$M" --subnet="$2" --gateway="$3" "$1"; else retry docker network create -d bridge --subnet="$2" --gateway="$3" "$1"; fi; }
ensure_net_overlay() { docker network inspect "$1" >/dev/null 2>&1 && { log "net $1 exists"; return 0; }; retry docker network create -d overlay --subnet="$2" "$1"; }
net_mtu() { case "${NEXUS_NET_MTU:-}" in "") : ;; auto) I=$(ip -4 route show default 2>/dev/null | awk "{print \$5; exit}"); [ -z "$I" ] && I=$(ls /sys/class/net 2>/dev/null | grep -v "^lo$" | head -1); [ -n "$I" ] && cat /sys/class/net/"$I"/mtu 2>/dev/null ;; *) echo "${NEXUS_NET_MTU}" ;; esac; }
net_report() { R=$(docker network inspect "$1" --format "driver={{.Driver}} subnet={{range .IPAM.Config}}{{.Subnet}}{{end}} gw={{range .IPAM.Config}}{{.Gateway}}{{end}} mtu={{index .Options \"com.docker.network.driver.mtu\"}}" 2>/dev/null | sed "s/mtu=<no value>/mtu=default/"); log "net $1 $R"; }
ensure_repo() { if [ -d /nexus-bucket/underground-nexus/.git ]; then git -C /nexus-bucket/underground-nexus pull --rebase >/dev/null 2>&1 || true; else mkdir -p /nexus-bucket; retry git clone https://github.com/Underground-Ops/underground-nexus.git /nexus-bucket/underground-nexus || true; fi; }
pkg_add() { command -v "$1" >/dev/null 2>&1 && return 0; apk add --no-cache "$2" >/dev/null 2>&1 || { apt-get update >/dev/null 2>&1 && apt-get install -y "$2" >/dev/null 2>&1; } || dnf install -y "$2" >/dev/null 2>&1 || true; command -v "$1" >/dev/null 2>&1; }
ensure_compose() { pkg_add docker-compose docker-compose || log "docker-compose not installable here - compose steps degrade"; }
ensure_swarm() { docker node ls >/dev/null 2>&1 && { log "swarm already active - joining existing"; return 0; }; docker swarm init >/dev/null 2>&1 && { log "swarm init ok"; return 0; }; A=$(ip -4 route get 1.1.1.1 2>/dev/null | awk "{print \$7; exit}"); [ -z "$A" ] && A=$(hostname -i 2>/dev/null | awk "{print \$1}"); [ -n "$A" ] && docker swarm init --advertise-addr "$A" >/dev/null 2>&1 && { log "swarm init ok (advertise $A)"; return 0; }; log "swarm init failed - overlay nets may degrade to bridge"; return 1; }
detect_substrate() { if [ -f /.dockerenv ] || [ -f /run/.containerenv ]; then NEXUS_METAL=0; else NEXUS_METAL=1; fi; DOCKER_BIN=$(command -v docker 2>/dev/null || echo /usr/local/bin/docker); NEXUS_ARCH=$(uname -m); if [ "$NEXUS_METAL" = "1" ]; then P_SSH="${P_SSH:-2223}"; P_DNS="${P_DNS:-5353}"; P_DHCP="${P_DHCP:-6767}"; P_S3="${P_S3:-19000}"; log "substrate: bare metal ($NEXUS_ARCH) - host publishes shifted ssh=$P_SSH dns=$P_DNS dhcp=$P_DHCP s3=$P_S3"; else P_SSH="${P_SSH:-22}"; P_DNS="${P_DNS:-53}"; P_DHCP="${P_DHCP:-67}"; P_S3="${P_S3:-9000}"; log "substrate: container ($NEXUS_ARCH) - canonical host publishes"; fi; log "docker cli at $DOCKER_BIN"; }

# ---- preflight: wait for dockerd, ensure repo, clean slate ----
wait_docker
detect_substrate
pkg_add git git || log "git unavailable - repo sync may skip"
ensure_repo
[ "${OLYMPIAD_CLEAN:-1}" = "1" ] && for c in Inner-DNS-Control Olympiad0 workbench Athena0 torpedo; do docker rm -f "$c" >/dev/null 2>&1 || true; done
ensure_swarm || true
ensure_compose
ensure_net_bridge Inner-Athena 10.20.0.0/24 10.20.0.1
net_report Inner-Athena
docker run -itd -p 800:80 -h Inner-DNS-Control --name=Inner-DNS-Control --net=Inner-Athena --ip=10.20.0.20 --restart=always -v pihole_DNS_data:/etc/dnsmasq.d/ -v pihole_config:/etc/pihole/ pihole/pihole:latest || true
wait_container Inner-DNS-Control
docker volume create portainer_data || true
docker run -d -p 8000:8000 -p 9443:9443 --name=Olympiad0 --dns=10.20.0.20 --net=Inner-Athena --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest || true
docker run -itd --name=workbench -h workbench --privileged -e PUID=1000 -e PGID=1000 -e TZ=America/Colorado -p 1000:3000 --dns=10.20.0.20 --net=Inner-Athena --restart=always -v workbench0:/config -v /nexus-bucket:/config/Desktop/nexus-bucket -v /var/run/docker.sock:/var/run/docker.sock linuxserver/webtop:ubuntu-mate || true
wait_exec workbench
docker exec workbench echo docker exec workbench sudo apt -y update >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo apt install -y wget >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo apt install -y git >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo apt install -y iputils-ping >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo wget https://github.com/shiftkey/desktop/releases/download/release-3.1.1-linux1/GitHubDesktop-linux-3.1.1-linux1.deb >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo dpkg -i GitHubDesktop-linux-3.1.1-linux1.deb >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo apt install -y apt-transport-https curl >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo dpkg -i chrome-remote-desktop_current_amd64.deb >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench wget https://release.gitkraken.com/linux/gitkraken-amd64.deb >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo dpkg -i gitkraken-amd64.deb >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo dpkg -i discord.deb >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo apt install -y qemu >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo apt install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils qemu-system qemu-system-x86 qemu-system-arm >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo apt install -y virt-manager >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo apt install -y synaptic >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec Athena0 sh /enable-weekly-updates.sh >> /nexus-bucket/enable-weekly-updates.sh || true
docker exec workbench echo docker exec workbench sudo wget https://raw.githubusercontent.com/Underground-Ops/underground-nexus/main/Terraform%20Master/terraform-workbench-install.sh >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo sh terraform-workbench-install.sh >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo mv /terraform-workbench-install.sh /config/Desktop/nexus-bucket >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo apt -y update --fix-missing >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo apt --fix-broken install -y >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo apt -y upgrade >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo apt install -y virt-manager >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo rm /usr/share/backgrounds/ubuntu-mate-jammy/Jammy-Jellyfish_WP_4096x2304_Green.png >> /nexus-bucket/workbench.sh || true
docker exec workbench echo docker exec workbench sudo wget https://raw.githubusercontent.com/Underground-Ops/underground-nexus/main/Wallpapers/underground-nexus-scifi-space-jelly.png -O /usr/share/backgrounds/ubuntu-mate-jammy/Jammy-Jellyfish_WP_4096x2304_Green.png >> /nexus-bucket/workbench.sh || true
docker run -itd --init --name=Athena0 -h Athena0 --dns=10.20.0.20 --net=Inner-Athena --restart=always -v athena0:/home/ -v /nexus-bucket:/nexus-bucket -v /etc/docker:/etc/docker -v ${DOCKER_BIN}:/usr/local/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes/:/var/lib/docker/volumes/ natoascode/athena0:latest || true
wait_exec Athena0
docker exec Athena0 apt -y update || true
docker exec Athena0 apt install -y iputils-ping || true
docker exec Athena0 git clone https://github.com/radareorg/radare2 || true
docker exec Athena0 sh radare2/sys/install.sh || true
docker exec Athena0 apt-get install -y metasploit-framework || true
docker exec Athena0 apt -y update || true
docker exec Athena0 apt -y upgrade || true
docker run -itd --privileged -p ${P_S3}:9000 -p 9010:9001 --name=torpedo -h torpedo --dns=10.20.0.20 --net=Inner-Athena --restart=always -v /nexus-bucket:/nexus-bucket -v /nexus-bucket/s3-torpedo:/data pgsty/minio:latest server /data --console-address :9001 || true
docker exec Athena0 sh /old-underground-nexus-dagger-ci.sh || true
docker exec Athena0 sh /nexus-bucket/underground-nexus/'Dagger CI'/Scripts/enable-weekly-updates.sh || true
docker exec workbench echo docker exec workbench bash /config/Desktop/nexus-bucket/underground-nexus/visual-studio-code.sh >> /nexus-bucket/workbench.sh || true
docker exec Athena0 sh /nexus-bucket/workbench.sh || true
docker exec workbench bash /config/Desktop/nexus-bucket/terraform-workbench-install.sh && docker exec workbench terraform -v || true
docker exec Athena0 curl https://raw.githubusercontent.com/Underground-Ops/underground-nexus/main/underground-nexus-update.sh | bash || true
docker restart Inner-DNS-Control || true