version: '3'

services:
   db:
     image: mariadb:latest
     deploy:
       resources:
         limits:
           cpus: '1.00'
           memory: 1024M
     volumes:
       - db_data:/var/lib/mysql
     restart: unless-stopped
     environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: bookstack
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: Apoll0HasSh03s148299
     networks:
      #- default
      #- Inner-Athena
      - traefik-public
     dns:
      - 10.20.0.1

   bookstack:
     depends_on:
       - db
     image: solidnerd/bookstack:latest
     ports:
       - 4180:8080
     environment:
      #APP_URL: knowledge.underground-ops.me
      DB_HOST: bookstack_db:3306
      DB_DATABASE: bookstack
      DB_USERNAME: bookstack
      DB_PASSWORD: Apoll0HasSh03s148299
     networks:
      #- default
      #- Inner-Athena
      - traefik-public
     dns:
      - 10.20.0.1
     deploy:
      resources:
        limits:
         cpus: '1.00'
         memory: 1024M
      labels:
        - traefik.port=4180
        - traefik.frontend.rule=Host(`knowledge.underground-ops.me`)
        # To hash password use (openssl passwd -apr1 | sed -E "s:[\$]:\$\$:g") - default password is "notiaPoint!1"
        ##- traefik.http.middlewares.bookstack-auth.basicauth.users=admin:$$apr1$$nIkVDmwy$$xkGIleRnQ0GJ6o96am.cb/
        - traefik.docker.network=proxy
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # https-redirect middleware to redirect HTTP to HTTPS
        # It can be re-used by other stacks in other Docker Compose files
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.bookstack-http.rule=Host(`knowledge.underground-ops.me`)
        - traefik.http.routers.bookstack-http.entrypoints=http
        - traefik.http.routers.bookstack-http.middlewares=https-redirect
        - traefik.http.routers.bookstack-https.rule=Host(`knowledge.underground-ops.me`)
        - traefik.http.routers.bookstack-https.entrypoints=https
        - traefik.http.routers.bookstack-https.tls=true
        - traefik.http.routers.bookstack-https.tls.certresolver=le
        # Enable HTTP Basic auth, using the middleware created above
        ##- traefik.http.routers.bookstack-https.middlewares=bookstack-auth
        - traefik.http.services.bookstack.loadbalancer.server.port=4180

volumes:
    db_data: {}
networks:
  Inner-Athena:
    external: true
  traefik-public:
    external: true