version: '3'

services:
   nextcloud:
     image: lscr.io/linuxserver/nextcloud:latest
     container_name: nextcloud
     volumes:
       - nextcloud_config:/config
       - cloud_data:/data
     ports:
       - 4000:443
     restart: unless-stopped
     environment:
       - PUID=1000
       - PGID=1000
     networks:
      #- default
      #- Inner-Athena
      - traefik-public
     dns:
      - 10.20.0.1
     deploy:
      resources:
        limits:
         cpus: '2.00'
         memory: 2048M
      labels:
        - traefik.port=80
        - traefik.frontend.rule=Host(cloud.underground-ops.me)
        # To hash password use (openssl passwd -apr1 | sed -E "s:[\$]:\$\$:g") - default password is "notiaPoint!1"
        ##- traefik.http.middlewares.nextcloud-auth.basicauth.users=admin:$$apr1$$nIkVDmwy$$xkGIleRnQ0GJ6o96am.cb/
        - traefik.docker.network=proxy
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # https-redirect middleware to redirect HTTP to HTTPS
        # It can be re-used by other stacks in other Docker Compose files
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.cloud-http.rule=Host(cloud.underground-ops.me)
        - traefik.http.routers.nextcloud-http.entrypoints=http
        - traefik.http.routers.nextcloud-http.middlewares=https-redirect
        - traefik.http.routers.nextcloud-https.rule=Host(cloud.underground-ops.me)
        - traefik.http.routers.nextcloud-https.entrypoints=https
        - traefik.http.routers.nextcloud-https.tls=true
        - traefik.http.routers.nextcloud-https.tls.certresolver=le
        # Enable HTTP Basic auth, using the middleware created above
        ##- traefik.http.routers.nextcloud-https.middlewares=nextcloud-auth
        - traefik.http.services.nextcloud.loadbalancer.server.port=80

volumes:
    nextcloud_config: {}
    cloud_data: {}
networks:
  Inner-Athena:
    external: true
  traefik-public:
    external: true